spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/emprestimo_homolog?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: qwerty

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect